namespace PBS.ERP.Shared.Models
{
    public static class DEFAULTS
    {
        public static readonly List<Field> Columns = new List<Field>
        {
            new Field
            {
                ColumnName = "ID",
                DisplayLabel = "ID",
                SectionNumber = 0,
                SectionName = "Table Key",
                SortOrder = 1,
                SqlType = "int identity",
                InputType = "auto-number",
                IsRequired = true,
                IsReadonly = true,
                IsComputed = false,
                AllowInsert = false,
                AllowUpdate = false,
                AllowDelete = true,
                ShowInList = false,
                IsSearchable = true,
                IsSortable = true,
                Exportable = true,
                Importable = true,
                ShowInMobile = true,
                Width=2
            },
            new Field
            {
                ColumnName = "UID",
                DisplayLabel = "UID",
                SectionNumber = 0,
                SectionName = "Table Key",
                SortOrder = 2,
                SqlType = "varchar",
                InputType = "auto-text",
                IsRequired = true,
                MaxLength = 100,
                IsReadonly = true,
                IsComputed = true,
                AllowInsert = false,
                AllowUpdate = false,
                AllowDelete = true,
                ShowInList = false,
                IsSearchable = true,
                IsSortable = true,
                Exportable = true,
                Importable = true,
                ShowInMobile = true,
                Width=2
            },
            new Field
            {
                ColumnName = "Remarks",
                DisplayLabel = "Remarks",
                SectionNumber = 10,
                SectionName = "System Generated Fields",
                SortOrder = 9,
                SqlType = "varchar",
                InputType = "text",
                MaxLength = 500,
                IsReadonly=false,
                AllowInsert = true,
                AllowUpdate = true,
                AllowDelete = true,
                ShowInList = false,
                IsSearchable = true,
                IsSortable = true,
                Exportable = true,
                Importable = true,
                ShowInMobile = true,
                Width=2
            },
            new Field
            {
                ColumnName = "CreatedTime",
                DisplayLabel = "Created Time",
                SectionNumber = 10,
                SectionName = "System Generated Fields",
                SortOrder = 3,
                SqlType = "datetime",
                InputType = "auto-time",
                IsReadonly = true,
                AllowInsert = false,
                AllowUpdate = false,
                AllowDelete = true,
                ShowInList = true,
                IsSearchable = true,
                IsSortable = true,
                Exportable = true,
                Importable = true,
                ShowInMobile = true,
                Width=2
            },
            new Field
            {
                ColumnName = "ModifiedTime",
                DisplayLabel = "Modified Time",
                SectionNumber = 10,
                SectionName = "System Generated Fields",
                SortOrder = 4,
                SqlType = "datetime",
                InputType = "auto-time",
                IsReadonly = true,
                AllowInsert = false,
                AllowUpdate = false,
                AllowDelete = true,
                ShowInList = true,
                IsSearchable = true,
                IsSortable = true,
                Exportable = true,
                Importable = true,
                ShowInMobile = true,
                Width=2
            },
            new Field
            {
                ColumnName = "DeletedTime",
                DisplayLabel = "Deleted Time",
                SectionNumber = 10,
                SectionName = "System Generated Fields",
                SortOrder = 5,
                SqlType = "datetime",
                InputType = "auto-time",
                IsReadonly = true,
                AllowInsert = false,
                AllowUpdate = false,
                AllowDelete = true,
                ShowInList = false,
                IsSearchable = true,
                IsSortable = true,
                Exportable = true,
                Importable = true,
                ShowInMobile = true,
                Width=2
            },
            new Field
            {
                ColumnName = "CreatedBy",
                DisplayLabel = "Created By",
                SectionNumber = 10,
                SectionName = "System Generated Fields",
                SortOrder = 6,
                SqlType = "varchar",
                InputType = "select",
                IsRequired = true,
                MaxLength = 100,
                IsReadonly = true,
                IsForeignKey = false,
                AllowInsert = false,
                AllowUpdate = false,
                AllowDelete = true,
                ShowInList = false,
                IsSearchable = true,
                IsSortable = true,
                Exportable = true,
                Importable = true,
                ShowInMobile = true,
                Width=2
            },
            new Field
            {
                ColumnName = "ModifiedBy",
                DisplayLabel = "Modified By",
                SectionNumber = 10,
                SectionName = "System Generated Fields",
                SortOrder = 7,
                SqlType = "varchar",
                InputType = "select",
                MaxLength = 100,
                IsReadonly = true,
                IsForeignKey = false,
                AllowInsert = false,
                AllowUpdate = false,
                AllowDelete = true,
                ShowInList = false,
                IsSearchable = true,
                IsSortable = true,
                Exportable = true,
                Importable = true,
                ShowInMobile = true,
                Width=2
            },
            new Field
            {
                ColumnName = "DeletedBy",
                DisplayLabel = "Deleted By",
                SectionNumber = 10,
                SectionName = "System Generated Fields",
                SortOrder = 8,
                SqlType = "varchar",
                InputType = "select",
                MaxLength = 100,
                IsReadonly = true,
                IsComputed = true,
                IsForeignKey = false,
                AllowInsert = false,
                AllowUpdate = false,
                AllowDelete = true,
                ShowInList = false,
                IsSearchable = true,
                IsSortable = true,
                Exportable = true,
                Importable = true,
                ShowInMobile = true,
                Width=2
            },
            new Field
            {
                ColumnName = "IsDeleted",
                DisplayLabel = "IsDeleted?",
                SectionNumber = 10,
                SectionName = "System Generated Fields",
                SortOrder = 10,
                SqlType = "bit",
                InputType = "boolean",
                IsRequired = true,
                IsReadonly = true,
                AllowInsert = false,
                AllowUpdate = false,
                AllowDelete = true,
                ShowInList = false,
                IsSearchable = true,
                IsSortable = true,
                Exportable = true,
                Importable = true,
                ShowInMobile = true,
                Width=2
            },
            new Field
            {
                ColumnName = "IsActive",
                DisplayLabel = "IsActive?",
                SectionNumber = 10,
                SectionName = "System Generated Fields",
                SortOrder = 8,
                SqlType = "bit",
                InputType = "boolean",
                IsRequired = false,
                IsReadonly = true,
                AllowInsert = false,
                AllowUpdate = false,
                AllowDelete = true,
                ShowInList = false,
                IsSearchable = true,
                IsSortable = true,
                Exportable = true,
                Importable = true,
                ShowInMobile = true,
                Width=2
            }
        };
           
    }
}